controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    drive_module_steering_angle_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    drive_module_velocity_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

drive_module_steering_angle_controller:
  ros__parameters:
    joints:
      - joint_chassis_to_steering_left_front
      - joint_chassis_to_steering_right_front
      - joint_chassis_to_steering_left_rear
      - joint_chassis_to_steering_right_rear
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false

drive_module_velocity_controller:
  ros__parameters:
    joints:
      - joint_steering_to_wheel_left_front
      - joint_steering_to_wheel_right_front
      - joint_steering_to_wheel_left_rear
      - joint_steering_to_wheel_right_rear
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    allow_integration_in_goal_trajectories: true
